[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
policy_pay = "2uJf3sxUpHXS7QR2thzUWmjnznhcDvnE7H87eDBJLUps"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./wallets/localnet.json"

[test]
startup_wait = 10000

[scripts]
test = "yarn run test:anchor:local"
